# Site settings
name: 
email: 923132714@qq.com
author: logic
url: url
resume_site: resume_site
github: github
description: Actually, less is more!
meta_description: 哈哈哈;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
# 头部文案
motto: 测试中。。。
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qq923132714

# Build settings
markdown: kramdown

baidu_analysis: d4e8841d030e4eef4a374e82513339ad

